### ISSUE TITLE
"Running the contributed command:'extension.enableAnimation' failed."

### ISSUE THREAD

**Issue by Qonsyuma** [spikespaz/vscode-smoothtype#9]
When trying to enable smooth typing, the message "Running the contributed command:'extension.enableAnimation' failed." pops up.
The extension has worked before fine, though after updating it doesn't seem to anymore.

Using VS Code Iniders:
```
Version: 1.28.0-insider (system setup)
Commit: 8330a695712c43f861ce5c47533d82637d3cb374
Date: 2018-09-13T11:25:00.283Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by spikespaz** [comment]
Can you send me the text in the output log?

**Comment by Qonsyuma** [comment]
There doesn't seem to be any text there

**Comment by rsperl** [comment]
VS Code Info:

```
% code --version
1.28.0-insider
d59d9f5aa5708c006e409c1a7b197c27fecb54a4
x64
```
When I toggle developer tools and try to enable smooth scrolling, this is what I get:

```
08:11:07.595 dom.ts:208 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
e @ dom.ts:208
p @ dom.ts:226
t._setListeningToMouseWheel @ scrollableElement.ts:317
t @ scrollableElement.ts:216
t @ scrollableElement.ts:483
t @ treeView.ts:521
e @ treeImpl.ts:99
i @ listService.ts:374
t.create @ types.ts:166
e._createInstance @ instantiationService.ts:120
e.createInstance @ instantiationService.ts:73
treeCreator @ quickOpenController.ts:181
t.create @ quickOpenWidget.ts:250
t.show @ quickOpenController.ts:186
o.run @ commandsHandler.ts:160
(anonymous) @ actions.ts:114
08:11:10.727 console.ts:136 [Extension Host] Check if cursor styles are injected. (at checkInjection (/Users/risugg/.vscode-insiders/extensions/spikespaz.vscode-smoothtype-1.1.3/extension.js:160:13))
08:11:10.731 dom.ts:208 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
e @ dom.ts:208
p @ dom.ts:226
t._setListeningToMouseWheel @ scrollableElement.ts:317
t @ scrollableElement.ts:216
t @ scrollableElement.ts:483
e @ listView.ts:99
e @ listWidget.ts:903
i @ listService.ts:222
t.create @ types.ts:166
e._createInstance @ instantiationService.ts:120
e.createInstance @ instantiationService.ts:73
t.createNotificationsList @ notificationsList.ts:76
t.show @ notificationsList.ts:52
t.addToast @ notificationsToasts.ts:146
t.onDidNotificationChange @ notificationsToasts.ts:89
(anonymous) @ notificationsToasts.ts:83
e.fire @ event.ts:140
t.notify @ notifications.ts:115
t.error @ notificationService.ts:50
t.onError @ commandsHandler.ts:328
(anonymous) @ commandsHandler.ts:313
m @ winjs.base.js:1230
enter @ winjs.base.js:916
_run @ winjs.base.js:1089
_error @ winjs.base.js:1062
e.resolveErr @ lazyPromise.ts:72
t._receiveReplyErr @ rpcProtocol.ts:422
t._receiveOneMessage @ rpcProtocol.ts:319
(anonymous) @ rpcProtocol.ts:149
e.fire @ event.ts:140
a @ ipc.net.ts:105
n._socketDataListener @ ipc.net.ts:134
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
08:11:10.732 event.ts:19 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
onFirstListenerAdd @ event.ts:19
Object.defineProperty.get._event._event @ event.ts:83
i @ event.ts:433
n @ event.ts:443
e @ listWidget.ts:456
e @ listWidget.ts:934
i @ listService.ts:222
t.create @ types.ts:166
e._createInstance @ instantiationService.ts:120
e.createInstance @ instantiationService.ts:73
t.createNotificationsList @ notificationsList.ts:76
t.show @ notificationsList.ts:52
t.addToast @ notificationsToasts.ts:146
t.onDidNotificationChange @ notificationsToasts.ts:89
(anonymous) @ notificationsToasts.ts:83
e.fire @ event.ts:140
t.notify @ notifications.ts:115
t.error @ notificationService.ts:50
t.onError @ commandsHandler.ts:328
(anonymous) @ commandsHandler.ts:313
m @ winjs.base.js:1230
enter @ winjs.base.js:916
_run @ winjs.base.js:1089
_error @ winjs.base.js:1062
e.resolveErr @ lazyPromise.ts:72
t._receiveReplyErr @ rpcProtocol.ts:422
t._receiveOneMessage @ rpcProtocol.ts:319
(anonymous) @ rpcProtocol.ts:149
e.fire @ event.ts:140
a @ ipc.net.ts:105
n._socketDataListener @ ipc.net.ts:134
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
08:11:10.745 notificationsAlerts.ts:39 Error: Running the contributed command:'extension.enableAnimation' failed.
    at e._executeContributedCommand (/Users/risugg/Dev/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:448:709)
    at e.$executeContributedCommand (/Users/risugg/Dev/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:449:90)
    at t._doInvokeHandler (/Users/risugg/Dev/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:630:888)
    at t._invokeHandler (/Users/risugg/Dev/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:630:554)
    at t._receiveRequest (/Users/risugg/Dev/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:629:126)
    at t._receiveOneMessage (/Users/risugg/Dev/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:628:59)
    at /Users/risugg/Dev/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:625:898
    at /Users/risugg/Dev/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:97:910
    at e.fire (/Users/risugg/Dev/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:218)
    at a (/Users/risugg/Dev/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:153:990)
    at Socket._socketDataListener (/Users/risugg/Dev/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:191)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
t.onDidNotificationChange @ notificationsAlerts.ts:39
(anonymous) @ notificationsAlerts.ts:27
e.fire @ event.ts:140
t.notify @ notifications.ts:115
t.error @ notificationService.ts:50
t.onError @ commandsHandler.ts:328
(anonymous) @ commandsHandler.ts:313
m @ winjs.base.js:1230
enter @ winjs.base.js:916
_run @ winjs.base.js:1089
_error @ winjs.base.js:1062
e.resolveErr @ lazyPromise.ts:72
t._receiveReplyErr @ rpcProtocol.ts:422
t._receiveOneMessage @ rpcProtocol.ts:319
(anonymous) @ rpcProtocol.ts:149
e.fire @ event.ts:140
a @ ipc.net.ts:105
n._socketDataListener @ ipc.net.ts:134
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
```

**Comment by spikespaz** [comment]
Are either of you perhaps using the user install of VS Code?

**Comment by spikespaz** [comment]
Open your terminal and type `where code` and paste that path here.

**Comment by rsperl** [comment]
`/Users/risugg/Dev/Visual Studio Code - Insiders.app/Contents/Resources/app/bin/code`

**Comment by spikespaz** [comment]
Oh are you both using a Mac? I don't directly support that system. I only have Windows and Linux to test it on.

**Comment by Qonsyuma** [comment]
I use Windows, and I am using the User installer, I prefer that one a lot more

**Comment by aleksander351** [comment]
Same problem with:
**Version: 1.28.0 (user setup)
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64**

**Comment by spikespaz** [comment]
This should be fixed in d8fc9d3. If it isn't, let me know, and I will reopen the issue.

**Comment by aleksander351** [comment]
VSC has now a built in "smooth-type" option: **Cursor Smooth Caret Animation**. (Version 1.30.2)

**Comment by spikespaz** [comment]
@aleksander351 I'm not sure what to do, VS Code doesn't apply this transition effect to every part of the interface, only the editor. It also doesn't allow customization. If the full extensibility of this extension were in VS Code, I would deprecate and archive it, but that's not the case...

**Comment by aleksander351** [comment]
That is true. You can not customize it, but it works for me. Good luck.

**Comment by Leonard18** [comment]
Same issue here. Someone, please help.

**Comment by ng-hai** [comment]
Not working on VS Code 1.38

`Running the contributed command: 'extension.enableAnimation' failed.`

**Comment by ntippman** [comment]
> Not working on VS Code 1.38
> 
> `Running the contributed command: 'extension.enableAnimation' failed.`

same issue on Ubuntu 19.04 with VS Code

```
1.38.0
3db7e09f3b61f915d03bbfa58e258d6eee843f35
x64
```

**Comment by spikespaz** [comment]
Please see recent changes to the README. I no longer actively support or develop this extension, its purpose is negated.
